In [2]:
# https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=2
import torch

x = torch.ones(2, 2, dtype=torch.float)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [4]:
print(x.size())

torch.Size([2, 2])


In [5]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x+y)

tensor([[0.8887, 1.0230],
        [1.1460, 1.6506]])


In [6]:
# inplace addition
y.add_(x)
# Every function with trailing underscore will do in place operation

tensor([[0.8887, 1.0230],
        [1.1460, 1.6506]])

In [9]:
x = torch.rand(3, 4)
print(x)
print(x[1, 2:])

tensor([[0.5479, 0.2890, 0.4759, 0.6456],
        [0.2846, 0.0521, 0.4834, 0.6566],
        [0.8480, 0.2816, 0.4129, 0.5446]])
tensor([0.4834, 0.6566])


In [11]:
x = torch.arange(4).view(2,2)
print(x)

tensor([[0, 1],
        [2, 3]])


In [14]:
# from numpy to troch.tensor
import numpy as np

a = np.random.rand(2,3)
a = torch.tensor(a)
print(a)

tensor([[0.3948, 0.4065, 0.1250],
        [0.2721, 0.4890, 0.5249]], dtype=torch.float64)


In [18]:
# from tensor to numpy
a = torch.rand(2, 3)
print(a.numpy())

[[0.8909623  0.14825207 0.2820357 ]
 [0.91137207 0.11951399 0.83375055]]


- if the tensor and the numpy array is in cpu, then modifying tensor or numpy arry will impact the other