## Gradient calculation
- requires_grad argument in defining tensor
- create a computational graph for every operation
- this will help to find the gradient by backpropagation

In [7]:
import torch

x = torch.randn(3, requires_grad=True)

print(x)

y = x+2
print(y)

z = y*y
z = z.mean()


tensor([ 0.3290, -2.2785,  2.3098], requires_grad=True)
tensor([ 2.3290, -0.2785,  4.3098], grad_fn=<AddBackward0>)


- printing y we can see the grad_fn
- calculate gradient y.backward()
  - dy/dx
  - x.grad

In [9]:
z.backward()
print(x.grad)

tensor([ 1.5527, -0.1857,  2.8732])


## to eliminate gradient tracking
- x.require_grad_(False)
  - inplace
- x.detach()
  - create a new tensor
- with torch.no_grad()